import { PasoFronterizo } from './types';

export const pasosFronterizos: PasoFronterizo[] = [
  {
    id: 'jama',
    nombre: 'Paso Jama',
    lat: -23.23,
    lng: -67.07,
    estado: 'abierto',
    region: 'Antofagasta',
    ultimaActualizacion: 'Hace 10 minutos',
    altitud: 4200,
    pronostico: [
      { dia: 'Lunes', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Martes', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Miércoles', icono: 'nublado', riesgo: 'medio' },
    ],
  },
  {
    id: 'san-francisco',
    nombre: 'Paso San Francisco',
    lat: -27.02,
    lng: -68.40,
    estado: 'precaucion',
    region: 'Atacama',
    ultimaActualizacion: 'Hace 45 minutos',
    altitud: 4726,
    pronostico: [
      { dia: 'Lunes', icono: 'nublado', riesgo: 'medio' },
      { dia: 'Martes', icono: 'nieve', riesgo: 'alto', alerta: 'Precaución por nevada' },
      { dia: 'Miércoles', icono: 'nieve', riesgo: 'alto' },
    ],
  },
  {
    id: 'agua-negra',
    nombre: 'Paso Agua Negra',
    lat: -30.17,
    lng: -69.82,
    estado: 'precaucion',
    region: 'Coquimbo',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 4765,
    pronostico: [
      { dia: 'Lunes', icono: 'nublado', riesgo: 'medio' },
      { dia: 'Martes', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'Miércoles', icono: 'nieve', riesgo: 'alto', alerta: 'Alerta de Tormenta Invernal' },
    ],
  },
  {
    id: 'cristo-redentor',
    nombre: 'Paso Cristo Redentor',
    subtitulo: 'Los Libertadores',
    lat: -32.82,
    lng: -70.07,
    estado: 'abierto',
    region: 'Valparaíso',
    ultimaActualizacion: 'Hace 15 minutos',
    altitud: 3200,
    pronostico: [
      { dia: 'Lunes', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Martes', icono: 'nublado', riesgo: 'medio' },
      { dia: 'Miércoles', icono: 'nieve', riesgo: 'alto', alerta: 'Alerta de Tormenta Invernal' },
    ],
  },
  {
    id: 'pehuenche',
    nombre: 'Paso Pehuenche',
    lat: -35.55,
    lng: -70.38,
    estado: 'cerrado',
    region: 'Maule',
    ultimaActualizacion: 'Hace 2 horas',
    altitud: 2553,
    pronostico: [
      { dia: 'Lunes', icono: 'nieve', riesgo: 'alto', alerta: 'Cerrado por nieve acumulada' },
      { dia: 'Martes', icono: 'nieve', riesgo: 'alto' },
      { dia: 'Miércoles', icono: 'nublado', riesgo: 'medio' },
    ],
  },
  {
    id: 'pino-hachado',
    nombre: 'Paso Pino Hachado',
    lat: -38.66,
    lng: -70.88,
    estado: 'abierto',
    region: 'La Araucanía',
    ultimaActualizacion: 'Hace 30 minutos',
    altitud: 1884,
    pronostico: [
      { dia: 'Lunes', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Martes', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Miércoles', icono: 'lluvia', riesgo: 'medio' },
    ],
  },
  {
    id: 'mamuil-malal',
    nombre: 'Paso Mamuil Malal',
    subtitulo: 'Tromen',
    lat: -39.43,
    lng: -71.38,
    estado: 'abierto',
    region: 'La Araucanía',
    ultimaActualizacion: 'Hace 20 minutos',
    altitud: 1207,
    pronostico: [
      { dia: 'Lunes', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Martes', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Miércoles', icono: 'nublado', riesgo: 'bajo' },
    ],
  },
  {
    id: 'cardinal-samore',
    nombre: 'Paso Cardenal Samoré',
    subtitulo: 'Anticura',
    lat: -40.72,
    lng: -71.58,
    estado: 'abierto',
    region: 'Los Lagos',
    ultimaActualizacion: 'Hace 5 minutos',
    altitud: 913,
    pronostico: [
      { dia: 'Lunes', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'Martes', icono: 'tormenta', riesgo: 'medio', alerta: 'Vientos fuertes' },
      { dia: 'Miércoles', icono: 'nublado', riesgo: 'bajo' },
    ],
  },
  {
    id: 'hua-hum',
    nombre: 'Paso Hua Hum',
    lat: -40.17,
    lng: -71.67,
    estado: 'precaucion',
    region: 'Los Ríos',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 659,
    pronostico: [
      { dia: 'Lunes', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'Martes', icono: 'tormenta', riesgo: 'alto', alerta: 'Lluvia intensa' },
      { dia: 'Miércoles', icono: 'lluvia', riesgo: 'medio' },
    ],
  },
  {
    id: 'vergara',
    nombre: 'Paso Vergara',
    subtitulo: 'Río Encuentro',
    lat: -43.83,
    lng: -71.88,
    estado: 'abierto',
    region: 'Aysén',
    ultimaActualizacion: 'Hace 40 minutos',
    altitud: 820,
    pronostico: [
      { dia: 'Lunes', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Martes', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'Miércoles', icono: 'lluvia', riesgo: 'medio' },
    ],
  },
];

export const regiones = [...new Set(pasosFronterizos.map((p) => p.region))].sort();
