import { PasoFronterizo } from './types';

export const pasosFronterizos: PasoFronterizo[] = [

  // ─── ARICA Y PARINACOTA ──────────────────────────────────────────────────────
  {
    id: 'visviri',
    nombre: 'Complejo Fronterizo Visviri',
    lat: -17.605,
    lng: -69.475,
    estado: 'abierto',
    region: 'Arica y Parinacota',
    ultimaActualizacion: 'Hace 20 minutos',
    altitud: 4070,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'sol', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'bajo' },
    ],
    climaActual: {
      temperatura: 14,
      sensacionTermica: 10,
      descripcion: 'Despejado y seco',
      icono: 'sol',
      viento: 15,
      humedad: 22,
      visibilidad: 40,
      presion: 620,
    },
  },
  {
    id: 'chungara',
    nombre: 'Complejo Fronterizo Integrado Chungará',
    subtitulo: 'Tambo Quemado',
    lat: -18.514,
    lng: -69.088,
    estado: 'abierto',
    region: 'Arica y Parinacota',
    ultimaActualizacion: 'Hace 35 minutos',
    altitud: 4517,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'nublado', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'nieve', riesgo: 'alto', alerta: 'Posible nevada altiplánica' },
    ],
    climaActual: {
      temperatura: 6,
      sensacionTermica: 0,
      descripcion: 'Soleado con viento',
      icono: 'sol',
      viento: 28,
      humedad: 30,
      visibilidad: 35,
      presion: 590,
    },
  },

  // ─── TARAPACÁ ────────────────────────────────────────────────────────────────
  {
    id: 'colchane',
    nombre: 'Complejo Fronterizo Colchane',
    lat: -19.275,
    lng: -68.647,
    estado: 'abierto',
    region: 'Tarapacá',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 3700,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'sol', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'bajo' },
    ],
    climaActual: {
      temperatura: 12,
      sensacionTermica: 8,
      descripcion: 'Cielo despejado',
      icono: 'sol',
      viento: 18,
      humedad: 25,
      visibilidad: 45,
      presion: 645,
    },
  },

  // ─── ANTOFAGASTA ─────────────────────────────────────────────────────────────
  {
    id: 'sico',
    nombre: 'Complejo Fronterizo Integrado SICO',
    lat: -23.768,
    lng: -67.643,
    estado: 'abierto',
    region: 'Antofagasta',
    ultimaActualizacion: 'Hace 50 minutos',
    altitud: 4079,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'sol', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'sol', riesgo: 'bajo' },
    ],
    climaActual: {
      temperatura: 15,
      sensacionTermica: 11,
      descripcion: 'Despejado',
      icono: 'sol',
      viento: 10,
      humedad: 20,
      visibilidad: 50,
      presion: 618,
    },
  },
  {
    id: 'jama',
    nombre: 'Complejo Fronterizo Jama',
    lat: -23.23,
    lng: -67.07,
    estado: 'abierto',
    region: 'Antofagasta',
    ultimaActualizacion: 'Hace 10 minutos',
    altitud: 4200,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'sol', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 18,
      sensacionTermica: 16,
      descripcion: 'Despejado',
      icono: 'sol',
      viento: 12,
      humedad: 35,
      visibilidad: 30,
      presion: 615,
    },
  },
  {
    id: 'ollague',
    nombre: 'Complejo Fronterizo Ollagüe',
    lat: -21.22,
    lng: -68.258,
    estado: 'abierto',
    region: 'Antofagasta',
    ultimaActualizacion: 'Hace 2 horas',
    altitud: 3696,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 13,
      sensacionTermica: 9,
      descripcion: 'Parcialmente despejado',
      icono: 'sol',
      viento: 20,
      humedad: 28,
      visibilidad: 40,
      presion: 650,
    },
  },
  {
    id: 'san-pedro-atacama',
    nombre: 'Complejo Fronterizo San Pedro de Atacama',
    lat: -22.92,
    lng: -67.62,
    estado: 'abierto',
    region: 'Antofagasta',
    ultimaActualizacion: 'Hace 30 minutos',
    altitud: 2407,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'sol', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'sol', riesgo: 'bajo' },
    ],
    climaActual: {
      temperatura: 22,
      sensacionTermica: 20,
      descripcion: 'Soleado y seco',
      icono: 'sol',
      viento: 8,
      humedad: 18,
      visibilidad: 50,
      presion: 760,
    },
  },

  // ─── ATACAMA ─────────────────────────────────────────────────────────────────
  {
    id: 'san-francisco',
    nombre: 'Complejo Fronterizo San Francisco',
    lat: -27.02,
    lng: -68.40,
    estado: 'precaucion',
    region: 'Atacama',
    ultimaActualizacion: 'Hace 45 minutos',
    altitud: 4726,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'medio' },
      { dia: 'Pasado', icono: 'nieve', riesgo: 'alto', alerta: 'Precaución por nevada' },
      { dia: 'D+3',    icono: 'nieve', riesgo: 'alto' },
    ],
    climaActual: {
      temperatura: -4,
      sensacionTermica: -11,
      descripcion: 'Nublado con nieve ligera',
      icono: 'nieve',
      viento: 38,
      humedad: 82,
      visibilidad: 5,
      presion: 580,
    },
  },

  // ─── COQUIMBO ────────────────────────────────────────────────────────────────
  {
    id: 'agua-negra',
    nombre: 'Complejo Fronterizo Agua Negra',
    lat: -30.17,
    lng: -69.82,
    estado: 'precaucion',
    region: 'Coquimbo',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 4765,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'medio' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'nieve', riesgo: 'alto', alerta: 'Alerta de Tormenta Invernal' },
    ],
    climaActual: {
      temperatura: 2,
      sensacionTermica: -5,
      descripcion: 'Parcialmente nublado',
      icono: 'nublado',
      viento: 28,
      humedad: 71,
      visibilidad: 12,
      presion: 585,
    },
  },

  // ─── VALPARAÍSO ──────────────────────────────────────────────────────────────
  {
    id: 'cristo-redentor',
    nombre: 'Complejo Fronterizo Los Libertadores',
    subtitulo: 'Cristo Redentor',
    lat: -32.82,
    lng: -70.07,
    estado: 'abierto',
    region: 'Valparaíso',
    ultimaActualizacion: 'Hace 15 minutos',
    altitud: 3200,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'nublado', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'nieve', riesgo: 'alto', alerta: 'Alerta de Tormenta Invernal' },
    ],
    climaActual: {
      temperatura: 8,
      sensacionTermica: 5,
      descripcion: 'Soleado',
      icono: 'sol',
      viento: 18,
      humedad: 48,
      visibilidad: 40,
      presion: 700,
    },
  },

  // ─── MAULE ───────────────────────────────────────────────────────────────────
  {
    id: 'pehuenche',
    nombre: 'Complejo Fronterizo Pehuenche',
    lat: -35.55,
    lng: -70.38,
    estado: 'cerrado',
    region: 'Maule',
    ultimaActualizacion: 'Hace 2 horas',
    altitud: 2553,
    pronostico: [
      { dia: 'Mañana', icono: 'nieve', riesgo: 'alto', alerta: 'Cerrado por nieve acumulada' },
      { dia: 'Pasado', icono: 'nieve', riesgo: 'alto' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: -8,
      sensacionTermica: -17,
      descripcion: 'Nevada intensa',
      icono: 'nieve',
      viento: 55,
      humedad: 93,
      visibilidad: 1,
      presion: 730,
    },
  },

  // ─── BIOBÍO ──────────────────────────────────────────────────────────────────
  {
    id: 'pichachen',
    nombre: 'Complejo Fronterizo Pichachén',
    lat: -37.40,
    lng: -71.25,
    estado: 'cerrado',
    region: 'Biobío',
    ultimaActualizacion: 'Hace 3 horas',
    altitud: 1618,
    pronostico: [
      { dia: 'Mañana', icono: 'nieve', riesgo: 'alto', alerta: 'Cerrado por acumulación de nieve' },
      { dia: 'Pasado', icono: 'nieve', riesgo: 'alto' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: -5,
      sensacionTermica: -12,
      descripcion: 'Nevada moderada',
      icono: 'nieve',
      viento: 45,
      humedad: 90,
      visibilidad: 2,
      presion: 835,
    },
  },

  // ─── LA ARAUCANÍA ────────────────────────────────────────────────────────────
  {
    id: 'pino-hachado',
    nombre: 'Complejo Fronterizo Pino Hachado',
    lat: -38.66,
    lng: -70.88,
    estado: 'abierto',
    region: 'La Araucanía',
    ultimaActualizacion: 'Hace 30 minutos',
    altitud: 1884,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 12,
      sensacionTermica: 10,
      descripcion: 'Cielos despejados',
      icono: 'sol',
      viento: 8,
      humedad: 60,
      visibilidad: 35,
      presion: 860,
    },
  },
  {
    id: 'icalma',
    nombre: 'Complejo Fronterizo Icalma',
    lat: -38.84,
    lng: -71.16,
    estado: 'precaucion',
    region: 'La Araucanía',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 1140,
    pronostico: [
      { dia: 'Mañana', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'Pasado', icono: 'nieve', riesgo: 'alto', alerta: 'Posible nevada en altura' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 5,
      sensacionTermica: 1,
      descripcion: 'Lluvia ligera',
      icono: 'lluvia',
      viento: 24,
      humedad: 85,
      visibilidad: 10,
      presion: 890,
    },
  },
  {
    id: 'mamuil-malal',
    nombre: 'Complejo Fronterizo Mamuil Malal',
    subtitulo: 'Tromen',
    lat: -39.43,
    lng: -71.38,
    estado: 'abierto',
    region: 'La Araucanía',
    ultimaActualizacion: 'Hace 20 minutos',
    altitud: 1207,
    pronostico: [
      { dia: 'Mañana', icono: 'sol', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'sol', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'bajo' },
    ],
    climaActual: {
      temperatura: 15,
      sensacionTermica: 14,
      descripcion: 'Despejado y soleado',
      icono: 'sol',
      viento: 6,
      humedad: 42,
      visibilidad: 50,
      presion: 880,
    },
  },
  {
    id: 'caririñe',
    nombre: 'Complejo Fronterizo Caririñe',
    lat: -39.50,
    lng: -71.64,
    estado: 'abierto',
    region: 'La Araucanía',
    ultimaActualizacion: 'Hace 45 minutos',
    altitud: 610,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 13,
      sensacionTermica: 10,
      descripcion: 'Parcialmente nublado',
      icono: 'nublado',
      viento: 14,
      humedad: 72,
      visibilidad: 28,
      presion: 960,
    },
  },

  // ─── LOS RÍOS ────────────────────────────────────────────────────────────────
  {
    id: 'hua-hum',
    nombre: 'Complejo Fronterizo Hua Hum',
    lat: -40.17,
    lng: -71.67,
    estado: 'precaucion',
    region: 'Los Ríos',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 659,
    pronostico: [
      { dia: 'Mañana', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'Pasado', icono: 'tormenta', riesgo: 'alto', alerta: 'Lluvia intensa' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 9,
      sensacionTermica: 5,
      descripcion: 'Lluvia moderada',
      icono: 'lluvia',
      viento: 32,
      humedad: 94,
      visibilidad: 8,
      presion: 1005,
    },
  },

  // ─── LOS LAGOS ───────────────────────────────────────────────────────────────
  {
    id: 'cardinal-samore',
    nombre: 'Complejo Fronterizo Cardenal Samoré',
    subtitulo: 'Anticura',
    lat: -40.72,
    lng: -71.58,
    estado: 'abierto',
    region: 'Los Lagos',
    ultimaActualizacion: 'Hace 5 minutos',
    altitud: 913,
    pronostico: [
      { dia: 'Mañana', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'tormenta', riesgo: 'medio', alerta: 'Vientos fuertes' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'bajo' },
    ],
    climaActual: {
      temperatura: 10,
      sensacionTermica: 7,
      descripcion: 'Llovizna ligera',
      icono: 'lluvia',
      viento: 22,
      humedad: 88,
      visibilidad: 20,
      presion: 1010,
    },
  },
  {
    id: 'peulla',
    nombre: 'Complejo Fronterizo Peulla',
    lat: -41.13,
    lng: -71.87,
    estado: 'abierto',
    region: 'Los Lagos',
    ultimaActualizacion: 'Hace 40 minutos',
    altitud: 350,
    pronostico: [
      { dia: 'Mañana', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'tormenta', riesgo: 'medio', alerta: 'Precipitaciones moderadas' },
    ],
    climaActual: {
      temperatura: 11,
      sensacionTermica: 8,
      descripcion: 'Lluvia persistente',
      icono: 'lluvia',
      viento: 19,
      humedad: 91,
      visibilidad: 15,
      presion: 1012,
    },
  },
  {
    id: 'limite-futaleufu',
    nombre: 'Complejo Fronterizo El Límite',
    subtitulo: 'Futaleufú',
    lat: -43.18,
    lng: -71.89,
    estado: 'abierto',
    region: 'Los Lagos',
    ultimaActualizacion: 'Hace 55 minutos',
    altitud: 515,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 8,
      sensacionTermica: 5,
      descripcion: 'Nublado con brisa',
      icono: 'nublado',
      viento: 16,
      humedad: 82,
      visibilidad: 22,
      presion: 1008,
    },
  },
  {
    id: 'rio-encuentro-palena',
    nombre: 'Complejo Fronterizo Río Encuentro',
    subtitulo: 'Palena',
    lat: -43.65,
    lng: -72.23,
    estado: 'abierto',
    region: 'Los Lagos',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 480,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 7,
      sensacionTermica: 3,
      descripcion: 'Cielo cubierto',
      icono: 'nublado',
      viento: 18,
      humedad: 85,
      visibilidad: 20,
      presion: 1006,
    },
  },

  // ─── AYSÉN ───────────────────────────────────────────────────────────────────
  {
    id: 'vergara',
    nombre: 'Complejo Fronterizo Vergara',
    subtitulo: 'Río Encuentro',
    lat: -43.83,
    lng: -71.88,
    estado: 'abierto',
    region: 'Aysén',
    ultimaActualizacion: 'Hace 40 minutos',
    altitud: 820,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 7,
      sensacionTermica: 4,
      descripcion: 'Cielo cubierto',
      icono: 'nublado',
      viento: 15,
      humedad: 80,
      visibilidad: 25,
      presion: 998,
    },
  },
  {
    id: 'coyhaique-alto',
    nombre: 'Complejo Fronterizo Coyhaique Alto',
    lat: -45.665,
    lng: -71.725,
    estado: 'abierto',
    region: 'Aysén',
    ultimaActualizacion: 'Hace 25 minutos',
    altitud: 1100,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'nieve', riesgo: 'alto', alerta: 'Nevada esperada en altura' },
    ],
    climaActual: {
      temperatura: 4,
      sensacionTermica: 0,
      descripcion: 'Parcialmente nublado',
      icono: 'nublado',
      viento: 20,
      humedad: 78,
      visibilidad: 18,
      presion: 890,
    },
  },
  {
    id: 'huemules',
    nombre: 'Complejo Fronterizo Huemules',
    lat: -45.18,
    lng: -71.93,
    estado: 'abierto',
    region: 'Aysén',
    ultimaActualizacion: 'Hace 50 minutos',
    altitud: 725,
    pronostico: [
      { dia: 'Mañana', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'bajo' },
    ],
    climaActual: {
      temperatura: 6,
      sensacionTermica: 2,
      descripcion: 'Lluvia ligera',
      icono: 'lluvia',
      viento: 22,
      humedad: 90,
      visibilidad: 16,
      presion: 1002,
    },
  },
  {
    id: 'jeinimeni',
    nombre: 'Complejo Fronterizo Jeinimeni',
    lat: -46.86,
    lng: -71.75,
    estado: 'abierto',
    region: 'Aysén',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 580,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 5,
      sensacionTermica: 1,
      descripcion: 'Nublado',
      icono: 'nublado',
      viento: 17,
      humedad: 84,
      visibilidad: 22,
      presion: 995,
    },
  },
  {
    id: 'ibanez-pallavicini',
    nombre: 'Complejo Ingeniero Ibáñez-Pallavicini',
    lat: -46.05,
    lng: -71.55,
    estado: 'precaucion',
    region: 'Aysén',
    ultimaActualizacion: 'Hace 30 minutos',
    altitud: 430,
    pronostico: [
      { dia: 'Mañana', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'Pasado', icono: 'tormenta', riesgo: 'alto', alerta: 'Vientos fuertes del sur' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 5,
      sensacionTermica: 0,
      descripcion: 'Lluvia con vientos fuertes',
      icono: 'lluvia',
      viento: 40,
      humedad: 92,
      visibilidad: 8,
      presion: 990,
    },
  },

  // ─── MAGALLANES ──────────────────────────────────────────────────────────────
  {
    id: 'dorotea',
    nombre: 'Complejo Fronterizo Dorotea',
    lat: -51.67,
    lng: -72.33,
    estado: 'abierto',
    region: 'Magallanes',
    ultimaActualizacion: 'Hace 20 minutos',
    altitud: 400,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'tormenta', riesgo: 'alto', alerta: 'Vientos del sur esperados' },
    ],
    climaActual: {
      temperatura: 3,
      sensacionTermica: -3,
      descripcion: 'Nublado y ventoso',
      icono: 'nublado',
      viento: 35,
      humedad: 87,
      visibilidad: 18,
      presion: 985,
    },
  },
  {
    id: 'casas-viejas',
    nombre: 'Complejo Fronterizo Casas Viejas',
    lat: -52.15,
    lng: -70.40,
    estado: 'abierto',
    region: 'Magallanes',
    ultimaActualizacion: 'Hace 35 minutos',
    altitud: 180,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 4,
      sensacionTermica: -1,
      descripcion: 'Parcialmente nublado',
      icono: 'nublado',
      viento: 28,
      humedad: 80,
      visibilidad: 25,
      presion: 988,
    },
  },
  {
    id: 'rio-don-guillermo',
    nombre: 'Complejo Fronterizo Río Don Guillermo',
    lat: -51.32,
    lng: -72.45,
    estado: 'abierto',
    region: 'Magallanes',
    ultimaActualizacion: 'Hace 1 hora',
    altitud: 300,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 2,
      sensacionTermica: -4,
      descripcion: 'Cielo cubierto',
      icono: 'nublado',
      viento: 30,
      humedad: 85,
      visibilidad: 20,
      presion: 990,
    },
  },
  {
    id: 'integracion-austral',
    nombre: 'Complejo Fronterizo Integración Austral',
    lat: -53.77,
    lng: -68.93,
    estado: 'precaucion',
    region: 'Magallanes',
    ultimaActualizacion: 'Hace 25 minutos',
    altitud: 10,
    pronostico: [
      { dia: 'Mañana', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'Pasado', icono: 'tormenta', riesgo: 'alto', alerta: 'Vientos Williwaw extremos' },
      { dia: 'D+3',    icono: 'nublado', riesgo: 'medio' },
    ],
    climaActual: {
      temperatura: 1,
      sensacionTermica: -7,
      descripcion: 'Vientos fuertes y lluvia',
      icono: 'tormenta',
      viento: 62,
      humedad: 92,
      visibilidad: 6,
      presion: 975,
    },
  },
  {
    id: 'san-sebastian',
    nombre: 'Complejo Fronterizo San Sebastián',
    lat: -53.24,
    lng: -68.77,
    estado: 'abierto',
    region: 'Magallanes',
    ultimaActualizacion: 'Hace 10 minutos',
    altitud: 15,
    pronostico: [
      { dia: 'Mañana', icono: 'nublado', riesgo: 'bajo' },
      { dia: 'Pasado', icono: 'lluvia', riesgo: 'medio' },
      { dia: 'D+3',    icono: 'tormenta', riesgo: 'medio', alerta: 'Vientos moderados esperados' },
    ],
    climaActual: {
      temperatura: 2,
      sensacionTermica: -5,
      descripcion: 'Parcialmente nublado',
      icono: 'nublado',
      viento: 38,
      humedad: 82,
      visibilidad: 20,
      presion: 980,
    },
  },
  {
    id: 'bellavista',
    nombre: 'Complejo Fronterizo Bellavista',
    lat: -52.28,
    lng: -73.54,
    estado: 'cerrado',
    region: 'Magallanes',
    ultimaActualizacion: 'Hace 6 horas',
    altitud: 5,
    pronostico: [
      { dia: 'Mañana', icono: 'tormenta', riesgo: 'alto', alerta: 'Cerrado por temporada' },
      { dia: 'Pasado', icono: 'tormenta', riesgo: 'alto' },
      { dia: 'D+3',    icono: 'lluvia', riesgo: 'alto' },
    ],
    climaActual: {
      temperatura: 1,
      sensacionTermica: -8,
      descripcion: 'Temporal con vientos fuertes',
      icono: 'tormenta',
      viento: 70,
      humedad: 95,
      visibilidad: 3,
      presion: 970,
    },
  },
];

export const regiones = [...new Set(pasosFronterizos.map((p) => p.region))].sort();
